In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.6.0'

In [3]:
A= tf . constant([[4,3],[6,1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]], dtype=int32)>

In [4]:
V= tf . Variable([[3,1],[4,5]])
V

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [4, 5]], dtype=int32)>

In [6]:
AV_concat=tf. concat(values=[A,V], axis=1)
AV_concat

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 3, 1],
       [6, 1, 4, 5]], dtype=int32)>

In [7]:
AV_concat=tf. concat(values=[A,V], axis=0)
AV_concat

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [3, 1],
       [4, 5]], dtype=int32)>

In [10]:
tensor=tf.zeros(shape=[3,4], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [9]:
tensor_ones=tf.ones(shape=[3,4], dtype=tf.int32)
tensor_ones

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [13]:
tensor_rand=tf.random.uniform(shape=[3,4], minval=4, maxval=10, dtype=tf.int32)
tensor_rand

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[5, 9, 9, 6],
       [4, 6, 4, 9],
       [4, 6, 7, 5]], dtype=int32)>

In [18]:
t_reshape=tf.reshape(tensor=tensor_rand,shape=[1,12])
t_reshape

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[5, 9, 9, 6, 4, 6, 4, 9, 4, 6, 7, 5]], dtype=int32)>

In [20]:
trans=tf.transpose(t_reshape)
trans

<tf.Tensor: shape=(12, 1), dtype=int32, numpy=
array([[5],
       [9],
       [9],
       [6],
       [4],
       [6],
       [4],
       [9],
       [4],
       [6],
       [7],
       [5]], dtype=int32)>

In [26]:

A_identity=tf.eye(num_rows=3, num_columns=3)
A_identity

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [28]:
row,col=AV_concat.shape
print(row)
col

4


2

In [29]:
A= tf . constant([[4,3],[6,1]])
B= tf . constant([[3,1],[5,4]])
AB_matmul=tf.matmul(A,B)
AB_matmul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[27, 16],
       [23, 10]], dtype=int32)>

In [30]:
AB_mul=tf.multiply(A,B)
AB_mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  3],
       [30,  4]], dtype=int32)>

In [31]:
A*3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  9],
       [18,  3]], dtype=int32)>

In [35]:
A= tf . constant([[4.1,3.2],[6.3,1.4]])
my_var=tf.Variable(A)
bool_var= tf.Variable([False,False,True])
complex_var=tf.Variable([2+4j, 6+3j])

In [42]:
print("Shape: ", my_var.shape)
print("DType: ", my_var.dtype)
my_var


Shape:  (2, 2)
DType:  <dtype: 'float32'>


<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[4.1, 3.2],
       [6.3, 1.4]], dtype=float32)>

In [37]:
print("Shape: ", bool_var.shape)
print("DType: ", bool_var.dtype)

Shape:  (3,)
DType:  <dtype: 'bool'>


In [38]:
print("Shape: ", complex_var.shape)
print("DType: ", complex_var.dtype)

Shape:  (2,)
DType:  <dtype: 'complex128'>


In [39]:
tf.reshape(my_var,[4,1])

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[4.1],
       [3.2],
       [6.3],
       [1.4]], dtype=float32)>

In [46]:
a=tf.Variable(my_var, name="John")
b=tf.Variable(my_var, name="John1")
print(a==b)

tf.Tensor(
[[ True  True]
 [ True  True]], shape=(2, 2), dtype=bool)


Sparse tensor

In [48]:
sparse_tensor=tf. sparse.SparseTensor(indices=[[0,0],[1,2]],values=[3,4], dense_shape=[3,4])
print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([3 4], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
