In [8]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

import tensorflow as tf


iris_data = load_iris() # load the iris dataset

print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(iris_data.target[:5])

x = iris_data.data
ye = iris_data.target.reshape(-1, 1) # Convert data to a single column

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(ye)
#print(y)

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)
type(train_x)

# Build the model

model = tf.keras.models.Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = tf.keras.optimizers.Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]
Neural Network Model Summary: 
Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 10)                50        
_________________________________________________________________
fc2 (Dense)                  (None, 10)                110       
_________________________________________________________________
output (Dense)               (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/200


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py:356: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


24/24 - 0s - loss: 1.1913 - accuracy: 0.0750
Epoch 2/200
24/24 - 0s - loss: 1.1344 - accuracy: 0.2083
Epoch 3/200
24/24 - 0s - loss: 1.0799 - accuracy: 0.1083
Epoch 4/200
24/24 - 0s - loss: 1.0334 - accuracy: 0.1667
Epoch 5/200
24/24 - 0s - loss: 0.9892 - accuracy: 0.4583
Epoch 6/200
24/24 - 0s - loss: 0.9428 - accuracy: 0.5667
Epoch 7/200
24/24 - 0s - loss: 0.8959 - accuracy: 0.6250
Epoch 8/200
24/24 - 0s - loss: 0.8513 - accuracy: 0.6417
Epoch 9/200
24/24 - 0s - loss: 0.8082 - accuracy: 0.7167
Epoch 10/200
24/24 - 0s - loss: 0.7617 - accuracy: 0.7167
Epoch 11/200
24/24 - 0s - loss: 0.7217 - accuracy: 0.7000
Epoch 12/200
24/24 - 0s - loss: 0.6835 - accuracy: 0.7750
Epoch 13/200
24/24 - 0s - loss: 0.6625 - accuracy: 0.7917
Epoch 14/200
24/24 - 0s - loss: 0.6157 - accuracy: 0.7000
Epoch 15/200
24/24 - 0s - loss: 0.5897 - accuracy: 0.9417
Epoch 16/200
24/24 - 0s - loss: 0.5582 - accuracy: 0.8833
Epoch 17/200
24/24 - 0s - loss: 0.5314 - accuracy: 0.9417
Epoch 18/200
24/24 - 0s - loss: 0.5